services:
  redis:
    image: redis:7-alpine
    container_name: video-translator-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
#   postgres:
#     image: postgres:16-alpine
#     container_name: video-translator-postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgre
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: video_translator
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres_data: